development:
    adapter: sqlite3
    database: db/development.sqlite3

test:
    adapter: mysql2
    database: tcktcrckt_test
    username: rails
    password: rails

production:
    adapter: mysql2
    database: tcktcrckt_production
    username: rails
    password: rails